### ISSUE TITLE
5.1 - poprawki

### ISSUE THREAD

**Issue by michal-bootcamp** [dave8git/javascript-prework#1]
- [ ] usuń niepotrzebne deklaracje parametrów funkcji
- [ ] niech funkcje pomocnicze `printMessage` i `clearMessages` będą zadeklarowane w pliku `functions.js`
- te zmienne: 
```
let playerMove, computerMove;
    let randomNumber;
```
zamień na stałe i od razu przypisuj im wartość

**Comment by dave8git** [comment]
Dzięki!
